# Site settings
title: The  Songwriting Experiment
description: > # this means to ignore newlines until "baseurl:"
  An experiment in writing pop music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.thesongwritingexperiment.com" # the base hostname & protocol for your site
twitter_username: LutherBaker
github_username:  TheSongwritingExperiment

# Build settings
markdown: kramdown
exclude: ["go.sh"]
